export const roles = [
  { value: 'Local', label: 'Local' },
  { value: 'Remote', label: 'Remote' },
];

export const specializations = [
  { value: 0, label: 'Therapist' },
  { value: 1, label: 'Anesthesiology' },
  { value: 2, label: 'Cardiology' },
  { value: 3, label: 'Allergist' },
  { value: 4, label: 'Bacteriologist' },
  { value: 5, label: 'Gastroenterologist' },
  { value: 6, label: 'Hematologist' },
  { value: 7, label: 'Dermatologist' },
  { value: 8, label: 'Nutritionist' },
  { value: 9, label: 'Endocrinologist' },
  { value: 10, label: 'Infectionist' },
  { value: 11, label: 'Beautician' },
  { value: 12, label: 'Mammologist' },
  { value: 13, label: 'Narcologist' },
  { value: 14, label: 'Neuropathologist' },
  { value: 15, label: 'Oncologist' },
  { value: 16, label: 'Orthopaedist' },
  { value: 17, label: 'Otorhinolaryngologist' },
  { value: 18, label: 'Ophthalmologist' },
  { value: 19, label: 'Psychiatrist' },
  { value: 20, label: 'Psychotherapist' },
  { value: 21, label: 'Pulmonologist' },
  { value: 22, label: 'Rehabilitator' },
  { value: 23, label: 'Rheumatologist' },
  { value: 24, label: 'Dentist' },
  { value: 25, label: 'Toxicologist' },
  { value: 26, label: 'Traumatologist' },
  { value: 27, label: 'Phoniatrician' },
  { value: 28, label: 'Physiologist' },
];

export const genders = [
  { value: 'Male', label: 'Male' },
  { value: 'Female', label: 'Female' },
];

export const countries = [
    { id: 0, value: 'AF', label: 'Afghanistan' },
    { id: 1, value: 'AL', label: 'Albania' },
    { id: 2, value: 'DZ', label: 'Algeria' },
    { id: 3, value: 'AD', label: 'Andorra' },
    { id: 4, value: 'AO', label: 'Angola' },
    { id: 5, value: 'AI', label: 'Anguilla' },
    { id: 6, value: 'AQ', label: 'Antarctica' },
    { id: 7, value: 'AG', label: 'Antigua and Barbuda' },
    { id: 8, value: 'AR', label: 'Argentina' },
    { id: 9, value: 'AM', label: 'Armenia' },
    { id: 10, value: 'AW', label: 'Aruba' },
    { id: 11, value: 'AU', label: 'Australia' },
    { id: 12, value: 'AT', label: 'Austria' },
    { id: 13, value: 'AZ', label: 'Azerbaijan' },
    { id: 14, value: 'BS', label: 'Bahamas' },
    { id: 15, value: 'BH', label: 'Bahrain' },
    { id: 16, value: 'BD', label: 'Bangladesh' },
    { id: 17, value: 'BB', label: 'Barbados' },
    { id: 18, value: 'BY', label: 'Belarus' },
    { id: 19, value: 'BE', label: 'Belgium' },
    { id: 20, value: 'BZ', label: 'Belize' },
    { id: 21, value: 'BJ', label: 'Benin' },
    { id: 22, value: 'BM', label: 'Bermuda' },
    { id: 23, value: 'BT', label: 'Bhutan' },
    { id: 24, value: 'BO', label: 'Bolivia' },
    { id: 25, value: 'BA', label: 'Bosnia and Herzegovina' },
    { id: 26, value: 'BW', label: 'Botswana' },
    { id: 27, value: 'BR', label: 'Brazil' },
    { id: 28, value: 'IO', label: 'British Indian Ocean Territory' },
    { id: 29, value: 'VG', label: 'British Virgin Islands' },
    { id: 30, value: 'BN', label: 'Brunei' },
    { id: 31, value: 'BG', label: 'Bulgaria' },
    { id: 32, value: 'BF', label: 'Burkina Faso' },
    { id: 33, value: 'BI', label: 'Burundi' },
    { id: 34, value: 'KH', label: 'Cambodia' },
    { id: 35, value: 'CM', label: 'Cameroon' },
    { id: 36, value: 'CA', label: 'Canada' },
    { id: 37, value: 'CV', label: 'Cape Verde' },
    { id: 38, value: 'KY', label: 'Cayman Islands' },
    { id: 39, value: 'CF', label: 'Central African Republic' },
    { id: 40, value: 'TD', label: 'Chad' },
    { id: 41, value: 'CL', label: 'Chile' },
    { id: 42, value: 'CN', label: 'China' },
    { id: 43, value: 'CX', label: 'Christmas Island' },
    { id: 44, value: 'CC', label: 'Cocos Islands' },
    { id: 45, value: 'CO', label: 'Colombia' },
    { id: 46, value: 'KM', label: 'Comoros' },
    { id: 47, value: 'CK', label: 'Cook Islands' },
    { id: 48, value: 'CR', label: 'Costa Rica' },
    { id: 49, value: 'HR', label: 'Croatia' },
    { id: 50, value: 'CU', label: 'Cuba' },
    { id: 51, value: 'CW', label: 'Curacao' },
    { id: 52, value: 'CY', label: 'Cyprus' },
    { id: 53, value: 'CZ', label: 'Czech Republic' },
    { id: 54, value: 'CD', label: 'Democratic Republic of the Congo' },
    { id: 55, value: 'DK', label: 'Denmark' },
    { id: 56, value: 'DJ', label: 'Djibouti' },
    { id: 57, value: 'DM', label: 'Dominica' },
    { id: 58, value: 'DO', label: 'Dominican Republic' },
    { id: 59, value: 'TL', label: 'East Timor' },
    { id: 60, value: 'EC', label: 'Ecuador' },
    { id: 61, value: 'EG', label: 'Egypt' },
    { id: 62, value: 'SV', label: 'El Salvador' },
    { id: 63, value: 'GQ', label: 'Equatorial Guinea' },
    { id: 64, value: 'ER', label: 'Eritrea' },
    { id: 65, value: 'EE', label: 'Estonia' },
    { id: 66, value: 'ET', label: 'Ethiopia' },
    { id: 67, value: 'FK', label: 'Falkland Islands' },
    { id: 68, value: 'FO', label: 'Faroe Islands' },
    { id: 69, value: 'FJ', label: 'Fiji' },
    { id: 70, value: 'FI', label: 'Finland' },
    { id: 71, value: 'FR', label: 'France' },
    { id: 72, value: 'PF', label: 'French Polynesia' },
    { id: 73, value: 'GA', label: 'Gabon' },
    { id: 74, value: 'GM', label: 'Gambia' },
    { id: 75, value: 'GE', label: 'Georgia' },
    { id: 76, value: 'DE', label: 'Germany' },
    { id: 77, value: 'GH', label: 'Ghana' },
    { id: 78, value: 'GI', label: 'Gibraltar' },
    { id: 79, value: 'GR', label: 'Greece' },
    { id: 80, value: 'GL', label: 'Greenland' },
    { id: 81, value: 'GD', label: 'Grenada' },
    { id: 82, value: 'GU', label: 'Guam' },
    { id: 83, value: 'GT', label: 'Guatemala' },
    { id: 84, value: 'GG', label: 'Guernsey' },
    { id: 85, value: 'GN', label: 'Guinea' },
    { id: 86, value: 'GW', label: 'Guinea-Bissau' },
    { id: 87, value: 'GY', label: 'Guyana' },
    { id: 88, value: 'HT', label: 'Haiti' },
    { id: 89, value: 'HN', label: 'Honduras' },
    { id: 90, value: 'HK', label: 'Hong Kong' },
    { id: 91, value: 'HU', label: 'Hungary' },
    { id: 92, value: 'IS', label: 'Iceland' },
    { id: 93, value: 'IN', label: 'India' },
    { id: 94, value: 'ID', label: 'Indonesia' },
    { id: 95, value: 'IR', label: 'Iran' },
    { id: 96, value: 'IQ', label: 'Iraq' },
    { id: 97, value: 'IE', label: 'Ireland' },
    { id: 98, value: 'IM', label: 'Isle of Man' },
    { id: 99, value: 'IL', label: 'Israel' },
    { id: 100, value: 'IT', label: 'Italy' },
    { id: 101, value: 'CI', label: 'Ivory Coast' },
    { id: 102, value: 'JM', label: 'Jamaica' },
    { id: 103, value: 'JP', label: 'Japan' },
    { id: 104, value: 'JE', label: 'Jersey' },
    { id: 105, value: 'JO', label: 'Jordan' },
    { id: 106, value: 'KZ', label: 'Kazakhstan' },
    { id: 107, value: 'KE', label: 'Kenya' },
    { id: 108, value: 'KI', label: 'Kiribati' },
    { id: 109, value: 'XK', label: 'Kosovo' },
    { id: 110, value: 'KW', label: 'Kuwait' },
    { id: 111, value: 'KG', label: 'Kyrgyzstan' },
    { id: 112, value: 'LA', label: 'Laos' },
    { id: 113, value: 'LV', label: 'Latvia' },
    { id: 114, value: 'LB', label: 'Lebanon' },
    { id: 115, value: 'LS', label: 'Lesotho' },
    { id: 116, value: 'LR', label: 'Liberia' },
    { id: 117, value: 'LY', label: 'Libya' },
    { id: 118, value: 'LI', label: 'Liechtenstein' },
    { id: 119, value: 'LT', label: 'Lithuania' },
    { id: 120, value: 'LU', label: 'Luxembourg' },
    { id: 121, value: 'MO', label: 'Macao' },
    { id: 122, value: 'MK', label: 'Macedonia' },
    { id: 123, value: 'MG', label: 'Madagascar' },
    { id: 124, value: 'MW', label: 'Malawi' },
    { id: 125, value: 'MY', label: 'Malaysia' },
    { id: 126, value: 'MV', label: 'Maldives' },
    { id: 127, value: 'ML', label: 'Mali' },
    { id: 128, value: 'MT', label: 'Malta' },
    { id: 129, value: 'MH', label: 'Marshall Islands' },
    { id: 130, value: 'MR', label: 'Mauritania' },
    { id: 131, value: 'MU', label: 'Mauritius' },
    { id: 132, value: 'YT', label: 'Mayotte' },
    { id: 133, value: 'MX', label: 'Mexico' },
    { id: 134, value: 'FM', label: 'Micronesia' },
    { id: 135, value: 'MD', label: 'Moldova' },
    { id: 136, value: 'MC', label: 'Monaco' },
    { id: 137, value: 'MN', label: 'Mongolia' },
    { id: 138, value: 'ME', label: 'Montenegro' },
    { id: 139, value: 'MS', label: 'Montserrat' },
    { id: 140, value: 'MA', label: 'Morocco' },
    { id: 141, value: 'MZ', label: 'Mozambique' },
    { id: 142, value: 'MM', label: 'Myanmar' },
    { id: 143, value: 'NA', label: 'Namibia' },
    { id: 144, value: 'NR', label: 'Nauru' },
    { id: 145, value: 'NP', label: 'Nepal' },
    { id: 146, value: 'NL', label: 'Netherlands' },
    { id: 147, value: 'NC', label: 'New Caledonia' },
    { id: 148, value: 'NZ', label: 'New Zealand' },
    { id: 149, value: 'NI', label: 'Nicaragua' },
    { id: 150, value: 'NE', label: 'Niger' },
    { id: 151, value: 'NG', label: 'Nigeria' },
    { id: 152, value: 'NU', label: 'Niue' },
    { id: 153, value: 'NF', label: 'Norfolk Island' },
    { id: 154, value: 'KP', label: 'North Korea' },
    { id: 155, value: 'MP', label: 'Northern Mariana Islands' },
    { id: 156, value: 'NO', label: 'Norway' },
    { id: 157, value: 'OM', label: 'Oman' },
    { id: 158, value: 'PK', label: 'Pakistan' },
    { id: 159, value: 'PW', label: 'Palau' },
    { id: 160, value: 'PS', label: 'Palestinian Territory' },
    { id: 161, value: 'PA', label: 'Panama' },
    { id: 162, value: 'PG', label: 'Papua New Guinea' },
    { id: 163, value: 'PY', label: 'Paraguay' },
    { id: 164, value: 'PE', label: 'Peru' },
    { id: 165, value: 'PH', label: 'Philippines' },
    { id: 166, value: 'PN', label: 'Pitcairn' },
    { id: 167, value: 'PL', label: 'Poland' },
    { id: 168, value: 'PT', label: 'Portugal' },
    { id: 169, value: 'PR', label: 'Puerto Rico' },
    { id: 170, value: 'QA', label: 'Qatar' },
    { id: 171, value: 'CG', label: 'Republic of the Congo' },
    { id: 172, value: 'RE', label: 'Reunion' },
    { id: 173, value: 'RO', label: 'Romania' },
    { id: 174, value: 'RU', label: 'Russia' },
    { id: 175, value: 'RW', label: 'Rwanda' },
    { id: 176, value: 'BL', label: 'Saint Barthelemy' },
    { id: 177, value: 'SH', label: 'Saint Helena' },
    { id: 178, value: 'KN', label: 'Saint Kitts and Nevis' },
    { id: 179, value: 'LC', label: 'Saint Lucia' },
    { id: 180, value: 'MF', label: 'Saint Martin' },
    { id: 181, value: 'PM', label: 'Saint Pierre and Miquelon' },
    { id: 182, value: 'VC', label: 'Saint Vincent and the Grenadines' },
    { id: 183, value: 'WS', label: 'Samoa' },
    { id: 184, value: 'SM', label: 'San Marino' },
    { id: 185, value: 'ST', label: 'Sao Tome and Principe' },
    { id: 186, value: 'SA', label: 'Saudi Arabia' },
    { id: 187, value: 'SN', label: 'Senegal' },
    { id: 188, value: 'RS', label: 'Serbia' },
    { id: 189, value: 'SC', label: 'Seychelles' },
    { id: 190, value: 'SL', label: 'Sierra Leone' },
    { id: 191, value: 'SG', label: 'Singapore' },
    { id: 192, value: 'SX', label: 'Sint Maarten' },
    { id: 193, value: 'SK', label: 'Slovakia' },
    { id: 194, value: 'SI', label: 'Slovenia' },
    { id: 195, value: 'SB', label: 'Solomon Islands' },
    { id: 196, value: 'SO', label: 'Somalia' },
    { id: 197, value: 'ZA', label: 'South Africa' },
    { id: 198, value: 'KR', label: 'South Korea' },
    { id: 199, value: 'SS', label: 'South Sudan' },
    { id: 200, value: 'ES', label: 'Spain' },
    { id: 201, value: 'LK', label: 'Sri Lanka' },
    { id: 202, value: 'SD', label: 'Sudan' },
    { id: 203, value: 'SR', label: 'Suriname' },
    { id: 204, value: 'SJ', label: 'Svalbard and Jan Mayen' },
    { id: 205, value: 'SZ', label: 'Swaziland' },
    { id: 206, value: 'SE', label: 'Sweden' },
    { id: 207, value: 'CH', label: 'Switzerland' },
    { id: 208, value: 'SY', label: 'Syria' },
    { id: 209, value: 'TW', label: 'Taiwan' },
    { id: 210, value: 'TJ', label: 'Tajikistan' },
    { id: 211, value: 'TZ', label: 'Tanzania' },
    { id: 212, value: 'TH', label: 'Thailand' },
    { id: 213, value: 'TG', label: 'Togo' },
    { id: 214, value: 'TK', label: 'Tokelau' },
    { id: 215, value: 'TO', label: 'Tonga' },
    { id: 216, value: 'TT', label: 'Trinidad and Tobago' },
    { id: 217, value: 'TN', label: 'Tunisia' },
    { id: 218, value: 'TR', label: 'Turkey' },
    { id: 219, value: 'TM', label: 'Turkmenistan' },
    { id: 220, value: 'TC', label: 'Turks and Caicos Islands' },
    { id: 221, value: 'TV', label: 'Tuvalu' },
    { id: 222, value: 'VI', label: 'U.S. Virgin Islands' },
    { id: 223, value: 'UG', label: 'Uganda' },
    { id: 224, value: 'UA', label: 'Ukraine' },
    { id: 225, value: 'AE', label: 'United Arab Emirates' },
    { id: 226, value: 'GB', label: 'United Kingdom' },
    { id: 227, value: 'US', label: 'United States' },
    { id: 228, value: 'UY', label: 'Uruguay' },
    { id: 229, value: 'UZ', label: 'Uzbekistan' },
    { id: 230, value: 'VU', label: 'Vanuatu' },
    { id: 231, value: 'VA', label: 'Vatican' },
    { id: 232, value: 'VE', label: 'Venezuela' },
    { id: 233, value: 'VN', label: 'Vietnam' },
    { id: 234, value: 'WF', label: 'Wallis and Futuna' },
    { id: 235, value: 'EH', label: 'Western Sahara' },
    { id: 236, value: 'YE', label: 'Yemen' },
    { id: 237, value: 'ZM', label: 'Zambia' },
    { id: 238, value: 'ZW', label: 'Zimbabwe' }
  ];

  export const timeZones = [
    {
      value: '(GMT-12) International Date Line West',
      label: '(GMT-12) International Date Line West',
    },
    { value: '(GMT-11) Niue', label: '(GMT-11:00) Niue' },
    { value: '(GMT-11) Samoa', label: '(GMT-11:00) Samoa' },
    {
      value: '(GMT-10) Hawaii-Aleutian',
      label: '(GMT-10) Hawaii-Aleutian',
    },
    { value: '(GMT-10) Cook Islands', label: '(GMT-10:00) Cook Islands' },
  
    { value: '(GMT-09) Alaska', label: '(GMT-09:00) Alaska' },
    {
      value: '(GMT-09) Gambier Islands',
      label: '(GMT-09) Gambier Islands',
    },
    {
      value: '(GMT-08) Pacific Time (US & Canada)',
      label: '(GMT-08) Pacific Time (US & Canada)',
    },
    {
      value: '(GMT-08) Baja California',
      label: '(GMT-08) Baja California',
    },
    {
      value: '(GMT-07) Mountain Time (US & Canada)',
      label: '(GMT-07) Mountain Time (US & Canada)',
    },
    {
      value: '(GMT-07) Chihuahua, La Paz, Mazatlan',
      label: '(GMT-07) Chihuahua, La Paz, Mazatlan',
    },
    { value: '(GMT-07) Arizona', label: '(GMT-07:00) Arizona' },
    {
      value: '(GMT-06) Central Time (US & Canada)',
      label: '(GMT-06) Central Time (US & Canada)',
    },
    {
      value: '(GMT-06) Central America',
      label: '(GMT-06) Central America',
    },
    { value: '(GMT-06) Mexico City', label: '(GMT-06:00) Mexico City' },
    { value: '(GMT-06) Monterrey', label: '(GMT-06:00) Monterrey' },
    {
      value: '(GMT-06) Mezcales, San Vicente, Bucerías',
      label: '(GMT-06) Mezcales, San Vicente, Bucerías',
    },
    {
      value: '(GMT-05) Eastern Time (US & Canada)',
      label: '(GMT-05) Eastern Time (US & Canada)',
    },
    {
      value: '(GMT-05) Bogota, Lima, Quito',
      label: '(GMT-05) Bogota, Lima, Quito',
    },
    { value: '(GMT-04) Caracas', label: '(GMT-04:30) Caracas' },
    {
      value: '(GMT-04) Atlantic Time (Canada)',
      label: '(GMT-04) Atlantic Time (Canada)',
    },
    { value: '(GMT-04) La Paz', label: '(GMT-04:00) La Paz' },
    { value: '(GMT-03) Newfoundland', label: '(GMT-03:30) Newfoundland' },
    { value: '(GMT-03) Buenos Aires', label: '(GMT-03:00) Buenos Aires' },
    { value: '(GMT-03) Brasilia', label: '(GMT-03:00) Brasilia' },
    { value: '(GMT-03) Montevideo', label: '(GMT-03:00) Montevideo' },
    { value: '(GMT-02) Mid-Atlantic', label: '(GMT-02:00) Mid-Atlantic' },
    { value: '(GMT-01) Azores', label: '(GMT-01:00) Azores' },
    { value: '(GMT-01) Cape Verde', label: '(GMT-01:00) Cape Verde' },
    { value: '(GMT-0) Greenwich Mean Time', label: '(GMT) Greenwich Mean Time' },
    {
      value: '    ',
      label: '(GMT-0) Dublin, Edinburgh, Lisbon, London',
    },
    {
      value: '(GMT+01) Amsterdam, Berlin, Rome, Vienna',
      label: '(GMT+01) Amsterdam, Berlin, Rome, Vienna',
    },
    {
      value: '(GMT+01) Brussels, Copenhagen, Madrid, Paris',
      label: '(GMT+01) Brussels, Copenhagen, Madrid, Paris',
    },
    {
      value: '(GMT+02) Athens, Bucharest, Istanbul',
      label: '(GMT+02) Athens, Bucharest, Istanbul',
    },
    { value: '(GMT+02) Cairo', label: '(GMT+02:00) Cairo' },
    { value: '(GMT+02) Jerusalem', label: '(GMT+02:00) Jerusalem' },
  
    { value: '(GMT+03) Nairobi', label: '(GMT+03:00) Nairobi' },
    {
      value: '(GMT+04) Abu Dhabi, Muscat',
      label: '(GMT+04) Abu Dhabi, Muscat',
    },
    { value: '(GMT+05) Ekaterinburg', label: '(GMT+05:00) Ekaterinburg' },
    {
      value: '(GMT+05) Islamabad, Karachi, Tashkent',
      label: '(GMT+05) Islamabad, Karachi, Tashkent',
    },
  
    { value: '(GMT+06) Astana, Dhaka', label: '(GMT+06:00) Astana, Dhaka' },
  
    {
      value: '(GMT+07) Bangkok, Hanoi, Jakarta',
      label: '(GMT+07) Bangkok, Hanoi, Jakarta',
    },
  ];

export const nameInfo = 'Patrick Beverley';
export const phoneNumberInfo = '+380660012300';
export const emailInfo = 'pat123beverley@gmail.com';
export const genderInfo = 'Male';
export const yearsInfo = '32 years';
export const cityCountryInfo = 'Leova, Moldova';
export const overviewInformation = 'overview information';
export const lastAppointmentInfo =
  'The average volume of RBCs, or the space each red blood cell fills, is measured through this test. ' +
  'Results outside of the normal range can be a sign of anemia or chronic fatigue. The average volume of RBCs, or the space each red blood cell fills, is measured through this test.' +
  'The average volume of RBCs, or the space each red blood cell fills, is measured through this test. ' +
  'Results outside of the normal range can be a sign of anemia or chronic fatigue. The average volume of RBCs, or the space each red blood cell fills, is measured through this test.';

