export type FieldName =
  | 'firstName'
  | 'lastName'
  | 'email'
  | 'phoneNumber'
  | 'password'
  | 'confirmPassword'
  | 'role'
  | 'address'
  | 'gender'
  | 'country'
  | 'city'
  | 'birthDate'
  | 'timeZone'
  | 'overview';
